package ftn.isa.domain;

public enum EquipmentType {
    DiagnosticEquipment, //reflex hammer, otoscope...
    TherapeuticEqupiment, // infusion pumps, nebulizer...
    PatientMobilityAids // wheelchair, cane...
}
